{
  "uid" : "7449a23d7955ed73",
  "name" : "test_login_0_admin",
  "fullName" : "scripts.test01_login.TestLogin#test_login_0_admin",
  "historyId" : "bb1dcc4d23cef927b8a64680869c2823",
  "time" : {
    "start" : 1608773719071,
    "stop" : 1608773738512,
    "duration" : 19441
  },
  "status" : "broken",
  "statusMessage" : "TypeError: a bytes-like object is required, not 'NoneType'",
  "statusTrace" : "self = <test01_login.TestLogin object at 0x00000258285C5250>, username = 'admin'\npwd = 'tydt_123456', code = '', expect_result = '系统管理'\n\n    @parameterized.expand(get_data())\n    def test_login(self,username, pwd, code, expect_result):\n        # 调用登录方法\n        self.login.page_login(username, pwd)\n        # 获取登录提示信息\n        msg = self.login.page_get_error_info()\n        # 断言\n        try:\n>           assert msg==expect_result\nE           AssertionError: assert '系统管理员' == '系统管理'\nE             - 系统管理\nE             + 系统管理员\nE             ?     +\n\ntest01_login.py:45: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\na = (<test01_login.TestLogin object at 0x00000258285C5250>,)\n\n    @wraps(func)\n    def standalone_func(*a):\n>       return func(*(a + p.args), **p.kwargs)\n\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\parameterized\\parameterized.py:530: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntest01_login.py:49: in test_login\n    allure.attach(self.login.base_get_image(), '截图' ,allure.attachment_type.PNG)\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\_allure.py:179: in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\nc:\\users\\guo\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\allure_pytest\\listener.py:220: in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\reporter.py:117: in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <allure_commons.logger.AllureFileLogger object at 0x0000025828564760>\nbody = None, file_name = '94456b37-e31f-4789-9117-47c8ecdf3abc-attachment.png'\n\n    @hookimpl\n    def report_attached_data(self, body, file_name):\n        destination = os.path.join(self._report_dir, file_name)\n        with open(destination, 'wb') as attached_file:\n            if isinstance(body, text_type):\n                attached_file.write(body.encode('utf-8'))\n            else:\n>               attached_file.write(body)\nE               TypeError: a bytes-like object is required, not 'NoneType'\n\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\logger.py:62: TypeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_Class__pytest_setup_class",
    "time" : {
      "start" : 1608773712116,
      "stop" : 1608773719069,
      "duration" : 6953
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "TypeError: a bytes-like object is required, not 'NoneType'",
    "statusTrace" : "self = <test01_login.TestLogin object at 0x00000258285C5250>, username = 'admin'\npwd = 'tydt_123456', code = '', expect_result = '系统管理'\n\n    @parameterized.expand(get_data())\n    def test_login(self,username, pwd, code, expect_result):\n        # 调用登录方法\n        self.login.page_login(username, pwd)\n        # 获取登录提示信息\n        msg = self.login.page_get_error_info()\n        # 断言\n        try:\n>           assert msg==expect_result\nE           AssertionError: assert '系统管理员' == '系统管理'\nE             - 系统管理\nE             + 系统管理员\nE             ?     +\n\ntest01_login.py:45: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\na = (<test01_login.TestLogin object at 0x00000258285C5250>,)\n\n    @wraps(func)\n    def standalone_func(*a):\n>       return func(*(a + p.args), **p.kwargs)\n\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\parameterized\\parameterized.py:530: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntest01_login.py:49: in test_login\n    allure.attach(self.login.base_get_image(), '截图' ,allure.attachment_type.PNG)\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\_allure.py:179: in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\nc:\\users\\guo\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\allure_pytest\\listener.py:220: in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\reporter.py:117: in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <allure_commons.logger.AllureFileLogger object at 0x0000025828564760>\nbody = None, file_name = '94456b37-e31f-4789-9117-47c8ecdf3abc-attachment.png'\n\n    @hookimpl\n    def report_attached_data(self, body, file_name):\n        destination = os.path.join(self._report_dir, file_name)\n        with open(destination, 'wb') as attached_file:\n            if isinstance(body, text_type):\n                attached_file.write(body.encode('utf-8'))\n            else:\n>               attached_file.write(body)\nE               TypeError: a bytes-like object is required, not 'NoneType'\n\nC:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\logger.py:62: TypeError",
    "steps" : [ {
      "name" : "输入用户名",
      "time" : {
        "start" : 1608773719071,
        "stop" : 1608773719179,
        "duration" : 108
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "username",
        "value" : "'admin'"
      } ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : true
    }, {
      "name" : "输入密码",
      "time" : {
        "start" : 1608773719179,
        "stop" : 1608773719303,
        "duration" : 124
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "pwd",
        "value" : "'tydt_123456'"
      } ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : true
    }, {
      "name" : "输入验证码",
      "time" : {
        "start" : 1608773721738,
        "stop" : 1608773736283,
        "duration" : 14545
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "img_path",
        "value" : "'D:/xi.png'"
      } ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : true
    }, {
      "name" : "点击登录",
      "time" : {
        "start" : 1608773736283,
        "stop" : 1608773736357,
        "duration" : 74
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    }, {
      "name" : "异常截图",
      "time" : {
        "start" : 1608773737201,
        "stop" : 1608773738509,
        "duration" : 1308
      },
      "status" : "broken",
      "statusMessage" : "TypeError: a bytes-like object is required, not 'NoneType'\n",
      "statusTrace" : "  File \"F:\\cim\\scripts\\test01_login.py\", line 49, in test_login\n    allure.attach(self.login.base_get_image(), '截图' ,allure.attachment_type.PNG)\n  File \"C:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 179, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"C:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"C:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"C:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n  File \"C:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"C:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"C:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\guo\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\allure_pytest\\listener.py\", line 220, in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"C:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\reporter.py\", line 117, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"C:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"C:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"C:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n  File \"C:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"C:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"C:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\GUO\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\logger.py\", line 62, in report_attached_data\n    attached_file.write(body)\n",
      "steps" : [ ],
      "attachments" : [ {
        "uid" : "f1640916000f3f8c",
        "name" : "截图",
        "source" : "f1640916000f3f8c.png",
        "type" : "image/png",
        "size" : 0
      } ],
      "parameters" : [ ],
      "attachmentsCount" : 1,
      "shouldDisplayMessage" : true,
      "stepsCount" : 0,
      "hasContent" : true
    } ],
    "attachments" : [ {
      "uid" : "5012b8a9986839dc",
      "name" : "log",
      "source" : "5012b8a9986839dc.txt",
      "type" : "text/plain",
      "size" : 2137
    } ],
    "parameters" : [ ],
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : true,
    "stepsCount" : 5,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "_Class__pytest_setup_class::0",
    "time" : {
      "start" : 1608773738602,
      "stop" : 1608773740803,
      "duration" : 2201
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "scripts"
  }, {
    "name" : "suite",
    "value" : "test01_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "Gxl"
  }, {
    "name" : "thread",
    "value" : "31428-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "scripts.test01_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "7449a23d7955ed73.json",
  "parameterValues" : [ ]
}